### ISSUE TITLE
Check if player is channelling 

### ISSUE THREAD

**Issue by Dairyman** [Smef/InteractiveFishingBobber#1]
Nice addon, small nit pick you need to check if `unitTarget` is `"player"`, the event fires for other players/party/raid members too.

e.g: 
```Lua
local function eventHandler(self, event, unitTarget, castGUID, spellID)
    if unitTarget ~= "player" then return end

   -- <snip>
end
```

**Comment by Smef** [comment]
Updated here and submitted to CurseForge. Thanks!
